---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argoproj
  labels:
    deploymentStrategy: helm
spec:
  project: default
  source:
    path: argocd/apps/metrics-server
    repoURL: git@github.com:NIXKnight/ArgoCD-Demo.git
    targetRevision: master
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
